// apps/digital-twin/system-management/src/renderer/features/Files2video.tsx
import { useState, useEffect, useMemo } from 'react'
import { ipcRenderer } from 'electron'
import DirectorySelector from '../components/DirectorySelector'

interface SelectorVal {
  title: string
  desc: string
  placeholder?: string
  directoryPath: string
}

interface Files2videoProps {
  buttonTitle?: string
}

export default function Files2video({ buttonTitle = "Select" }: Files2videoProps) {
  const [selectors, setSelectors] = useState<SelectorVal[]>([
    {
      title: "General Folder:",
      desc: "the files in General will be used in all videos(Intro, Closer...)",
      directoryPath: ""
    },
    {
      title: "Widgets Folder:",
      desc: "a folder with files related to a platform",
      directoryPath: ""
    },
    {
      title: "Platform Folder:",
      desc: "a folder with sub-folders, each of them related to a different widget.",
      directoryPath: ""
    }
  ])
  const [videoPaths, setVideoPaths] = useState<string[]>([])

  const hasSelected = useMemo(() => 
    selectors.filter(selector => selector.directoryPath).length === selectors.length,
    [selectors]
  )

  async function pathChangeHandler(index: number, directoryPath: string) {
    const newSelectors = [...selectors]
    newSelectors[index].directoryPath = directoryPath
    setSelectors(newSelectors)
    
    const result: { names: string[], paths: string[] } = await ipcRenderer.invoke("readFileInDirectory", directoryPath)
    setVideoPaths(result.paths.filter(path => path.match(/.(mp4|flv)$/) !== null))
  }

  async function generateVideo() {
    if (videoPaths.length === 0) {
      return Promise.reject("没有视频")
    }
    
    const updatedSelectors = selectors.map(selector => ({
      ...selector,
      title: 'Please ' + selector.title.toLowerCase()
    }))
    setSelectors(updatedSelectors)
    
    return await ipcRenderer.invoke("mergeVideo", videoPaths.map(item => String(item)))
  }

  useEffect(() => {
    const defaultDirectory = localStorage.getItem("Files2video:Directory")
    if (!defaultDirectory) return
  }, [])

  return (
    <div className="file2video">
      <ul className="list list-select">
        {selectors.map((s, sIndex) => (
          <li key={s.title} className="item item-select">
            <DirectorySelector 
              title={s.title}
              buttonTitle={buttonTitle}
              placeholder={s.placeholder}
              onPathChange={(filePaths) => pathChangeHandler(sIndex, filePaths)}
            />
          </li>
        ))}
      </ul>
      <button 
        className={`btn btn-generate ${hasSelected ? 'active' : 'no-active'}`}
        onClick={generateVideo}
      >
        GENERATE
      </button>
    </div>
  )
}

// desktop/src/renderer/features/Files2video.vue
<template lang="pug">
.file2video
  ul.list.list-select
    li.item.item-select(v-for="(s, sIndex) in selectors" :key="s.title")
      directory-selector(:title="s.title" :button-title="props.buttonTitle" :placeholder="s.placeholder" @pathChange="filePaths => pathChangeHandler(sIndex, filePaths)")
  button.btn.btn-generate(:class="hasSelected ? ' active' : ' no-active'" @click="generateVideo") GENERATE
</template>
<style lang="sass" scoped>
.btn.active
  background: red
</style>
<script lang="ts" setup>
import {ipcRenderer} from "electron"
import {ref, reactive, computed, onMounted} from "vue"
import DirectorySelector from "../components/DirectorySelector.vue"

interface SelectorVal {
  title: string,
  desc: string,
  placeholder?: string,
  directoryPath: string
}

type SelectorKey = "general" | "widget" | "platform"
type Selector = Record<SelectorKey, Extract<SelectorVal, { key: string }>>

// type Props = { buttonTitle?: string } & Selector
interface Props {
  buttonTitle?: string
}

const props = withDefaults(defineProps<Props>(), {
  buttonTitle: "Select"
})
let selectors = reactive<SelectorVal[]>([
  {
    title: "General Folder:",
    desc: "the files in General will be used in all videos(Intro, Closer...)",
    directoryPath: ""
  },
  {
    title: "Widgets Folder:",
    desc: "a folder with files related to a platform",
    directoryPath: ""
  },
  {
    title: "Platform Folder:",
    desc: "a folder with sub-folders, each of them related to a different widget.",
    directoryPath: ""
  }
])
let videoPaths = ref<string[]>([])

const hasSelected = computed(() => selectors.filter(selector => selector.directoryPath).length === selectors.length)

async function pathChangeHandler(index: number, directoryPath: string) {
  selectors[index].directoryPath = directoryPath
  // window.desktop.Files2videoPathChangeHandler(directoryPath)
  const result: { names: string[], paths: string[] } = await ipcRenderer.invoke("readFileInDirectory", directoryPath)
  videoPaths.value = result.paths.filter(path => path.match(/.(mp4|flv)$/) !== null)
}

async function generateVideo() {
  if (videoPaths.value.length === 0) {
    return Promise.reject("没有视频")
  }
  return await ipcRenderer.invoke("mergeVideo", videoPaths.value.map(item => String(item)))
}

onMounted(async () => {
  const defaultDirectory = localStorage.getItem("Files2video:Directory")
  if (!defaultDirectory) return false
})
</script>
<script lang="ts">
export default {
  name: "Files2video"
}
</script>
