// apps/digital-twin/system-management/src/renderer/components/DirectorySelector.tsx
import { useState, useMemo } from 'react'
import { dialog } from '@electron/remote'

interface DirectorySelectorProps {
  title?: string
  buttonTitle?: string
  dialogTitle?: string
  placeholder?: string
  value?: string
  onButtonClick?: () => void
  onPathChange?: (path: string) => void
}

export default function DirectorySelector({
  title = "",
  buttonTitle = "选择",
  dialogTitle = "请选择文件夹",
  placeholder = "",
  value = "",
  onButtonClick,
  onPathChange
}: DirectorySelectorProps) {
  const [directory, setDirectory] = useState(value)

  const inputTip = useMemo(() => 
    directory ? `You're selected ${directory}` : `Please select a directory for ${title}`,
    [directory, title]
  )

  async function handleButtonClick() {
    onButtonClick?.()
    const openResult = await dialog.showOpenDialog({
      title: dialogTitle,
      defaultPath: directory,
      properties: ["openDirectory"]
    })
    if (openResult.canceled) return
    const newPath = openResult.filePaths[0]
    setDirectory(newPath)
    onPathChange?.(newPath)
  }

  return (
    <>
      <label htmlFor={title}>{title}</label>
      <input
        type="text"
        readOnly
        value={directory}
        id={title}
        placeholder={placeholder}
        title={inputTip}
      />
      <button type="button" onClick={handleButtonClick}>
        {buttonTitle}
      </button>
    </>
  )
}

// system-management/src/renderer/components/DirectorySelector.vue
<template lang="pug">
label(:for="props.title") {{ props.title }}
input(type="text" readonly :value="directory" :id="props.title" :placeholder="props.placeholder" :title="inputTip")
button(type="button" @click="buttonHandler") {{ props.buttonTitle }}
</template>
<script setup lang="ts">
import {dialog} from "@electron/remote"
import {ref, getCurrentInstance, computed} from "vue"

const props = withDefaults(defineProps<{
  title?: string,
  buttonTitle?: string,
  dialogTitle?: string,
  placeholder?: string,
  value?: string
}>(), {
  title: "",
  buttonTitle: "选择",
  dialogTitle: "请选择文件夹",
  placeholder: "",
  value: ""
})
const directory = ref(props.value)
const inputTip = computed(() => directory.value ? `You're selected ${directory.value}` : `Please select a directory for ${props.title}`)
const emits = defineEmits(["buttonClick", "pathChange"])

async function buttonHandler() {
  emits("buttonClick")
  const openResult = await dialog.showOpenDialog({
    title: props.dialogTitle,
    defaultPath: directory.value,
    properties: ["openDirectory"]
  })
  if (openResult.canceled) return false
  directory.value = openResult.filePaths[0]
  emits("pathChange", directory.value)
}
</script>
<script lang="ts">
export default {
  name: "DirectorySelector",
  data() {
    return {}
  }
}
</script>

<style scoped>

</style>
